name: DayTypeGenerator
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - cycler=0.10.0=py38_0
  - freetype=2.9.1=ha9979f8_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - intel-openmp=2020.1=216
  - joblib=0.15.1=py_0
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.2.0=py38h74a9793_0
  - libpng=1.6.37=h2a8f88b_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38h64f37c6_0
  - mkl=2020.1=216
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.0.15=py38h14836fe_0
  - mkl_random=1.1.0=py38hf9181ef_0
  - numpy=1.18.1=py38h93ca92e_0
  - numpy-base=1.18.1=py38hc3f5095_1
  - openssl=1.1.1g=he774522_0
  - pandas=1.0.3=py38h47e9c7a_0
  - pip=20.0.2=py38_3
  - plotly=4.7.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38ha925a31_4
  - python=3.8.3=he1778fa_0
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - qt=5.9.7=vc14h73c81de_0
  - retrying=1.3.3=py_2
  - scikit-learn=0.22.1=py38h6288b17_0
  - scipy=1.4.1=py38h9439919_0
  - setuptools=46.4.0=py38_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h2a8f88b_1
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.2=py38_0
  - wincertstore=0.2=py38_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - altair==4.1.0
    - astor==0.8.1
    - attrs==19.3.0
    - backcall==0.1.0
    - base58==2.0.0
    - bleach==3.1.5
    - blinker==1.4
    - boto3==1.13.15
    - botocore==1.16.15
    - cachetools==4.1.0
    - chardet==3.0.4
    - click==7.1.2
    - colorama==0.4.3
    - decorator==4.4.2
    - defusedxml==0.6.0
    - docutils==0.15.2
    - entrypoints==0.3
    - enum-compat==0.0.3
    - idna==2.9
    - ipykernel==5.3.0
    - ipython==7.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.0
    - jinja2==2.11.2
    - jmespath==0.10.0
    - jsonschema==3.2.0
    - jupyter-client==6.1.3
    - jupyter-core==4.6.3
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - notebook==6.0.3
    - packaging==20.4
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pathtools==0.1.2
    - pickleshare==0.7.5
    - pillow==7.1.2
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - protobuf==3.11.3
    - pydeck==0.3.1
    - pygments==2.6.1
    - pyrsistent==0.16.0
    - pywin32==227
    - pywinpty==0.5.7
    - pyzmq==19.0.1
    - requests==2.23.0
    - s3transfer==0.3.3
    - send2trash==1.5.0
    - streamlit==0.60.0
    - terminado==0.8.3
    - testpath==0.4.4
    - toml==0.10.1
    - toolz==0.10.0
    - tornado==5.1.1
    - traitlets==4.3.3
    - tzlocal==2.1
    - urllib3==1.25.9
    - validators==0.15.0
    - watchdog==0.10.2
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
prefix: C:\ProgramData\Anaconda3\envs\alecstest

